-- Create table statements
-- Ensure tables are created cleanly before the Spring JPA 'update'
DROP TABLE IF EXISTS resume_data;
DROP TABLE IF EXISTS application;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS candidate;

CREATE TABLE candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    headline VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description CLOB,
    required_skills CLOB,
    location VARCHAR(255),
    is_active BOOLEAN,
    posted_date TIMESTAMP
);

CREATE TABLE application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT REFERENCES candidate(id),
    job_id BIGINT REFERENCES job(id),
    applied_date TIMESTAMP,
    status VARCHAR(255),
    screening_score DOUBLE
);

CREATE TABLE resume_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT REFERENCES application(id),
    original_file_name VARCHAR(255),
    parsed_name VARCHAR(255),
    parsed_email VARCHAR(255),
    parsed_phone VARCHAR(255),
    parsed_skills CLOB,
    raw_text CLOB
);